version: '3'

services:

  # PHP Service
  app:
    build:
      context: ./Docker/
      dockerfile: php/Dockerfile
    image: projectname/php
    container_name: laravel123_app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - ./Docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
       - ./storage:/var/www/html/storage
      - ./bootstrap/cache:/var/www/html/bootstrap/cache
    networks:
      - app-network
    depends_on:
      - db

  # Nginx Service
  webserver:
    image: nginx:alpine
    container_name: projectname_webserver
    restart: unless-stopped
    tty: true
    ports:
      - "8000:80"
      - "443:443"
    volumes:
      - ./:/var/www/html
      - ./Docker/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - app-network
    depends_on:
      - app

  # MySQL Service
  db:
    image: mysql:8.0.31
    container_name: laravel1_db
    restart: unless-stopped
    tty: true
    ports:
      - "33060:3306"
    environment:
      MYSQL_DATABASE: laravel1_db
      MYSQL_USER: userlaravel1  
      MYSQL_PASSWORD: minh@123
      MYSQL_ROOT_PASSWORD: minh@123
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./.data:/var/lib/mysql/
      - ./Docker/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - app-network

# Docker Networks
networks:
  app-network:
    driver: bridge

# Volumes
volumes:
  dbdata:
    driver: local
